[project]
name = "insightgenie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.5.5",
    "langchain>=1.3.14",
    "langchain-openai>=1.4.3",
    "langgraph>=1.2.10",
    "langwatch>=0.2.0",
    "pandas>=3.0.5",
    "pydantic>=2.13.4",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.2",
]
